### ISSUE TITLE
Can it be helpful for understanding vistual transformers?

### ISSUE THREAD

**Issue by guanfuchen** [jacobgil/vit-explain#1]
I am interesting why vistual transformers work better. Can it be helpful and how can I run it?

**Comment by jacobgil** [comment]
Hi, I added a hopefully detailed Readme shortly after you opened the issue (everything is hot from the oven!).
A blog post is planned soon.
I think these visualizations, and also tinkering with these transformers under the hood, can definitely help understand more what's going on inside them.
